ADD workflow

diff --git a/.github/actions/publish-pypi-version-check/action.yml b/.github/actions/publish-pypi-version-check/action.yml
--- a/.github/actions/publish-pypi-version-check/action.yml
+++ b/.github/actions/publish-pypi-version-check/action.yml
@@ -30,11 +30,11 @@ runs:
         echo "pip index $url_param versions ${{ env.APP_PACKAGE_NAME }} | grep Available"
         pip index $url_param versions ${{ env.APP_PACKAGE_NAME }} | grep Available
         
-        echo "pip index $url_param versions ${{ env.APP_PACKAGE_NAME }} | grep Available | grep --color=always \"$package_version\""
+        echo "pip index $url_param versions ${{ env.APP_PACKAGE_NAME }} | grep Available | grep --color=always \"$package_version\" || echo \"Not found\""
         pip index $url_param versions ${{ env.APP_PACKAGE_NAME }} | grep Available | grep --color=always "$package_version"
         
         versions=$(pip index $url_param versions ${{ env.APP_PACKAGE_NAME }} | grep Available)
-        echo -e "Versions available in repo: \n$( echo "$versions" | grep --color=always "$package_version" )"
+        echo -e "Versions available in repo: \n$( echo "$versions" | grep --color=always "$package_version" || echo \"Not found\" )"
 
         exists="$(echo "$versions" | grep "$package_version" > /dev/null 2>&1 && echo 'true' || echo 'false' )"
         if [ "$exists" == "true" ]; then
