ADD workflow

diff --git a/.github/actions/publish-pypi-version-check/action.yml b/.github/actions/publish-pypi-version-check/action.yml
--- a/.github/actions/publish-pypi-version-check/action.yml
+++ b/.github/actions/publish-pypi-version-check/action.yml
@@ -31,7 +31,7 @@ runs:
         pip index $url_param versions ${{ env.APP_PACKAGE_NAME }} | grep Available
         
         echo "pip index $url_param versions ${{ env.APP_PACKAGE_NAME }} | grep Available | grep --color=always \"$package_version\" || echo \"Not found\""
-        pip index $url_param versions ${{ env.APP_PACKAGE_NAME }} | grep Available | grep --color=always "$package_version"
+        pip index $url_param versions ${{ env.APP_PACKAGE_NAME }} | grep Available | grep --color=always "$package_version" || echo "Not found"
         
         versions=$(pip index $url_param versions ${{ env.APP_PACKAGE_NAME }} | grep Available)
         echo -e "Versions available in repo: \n$( echo "$versions" | grep --color=always "$package_version" || echo \"Not found\" )"
